apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecr-proxy.fullname" . }}-config
  labels:
    {{- include "ecr-proxy.labels" . | nindent 4 }}
data:
  allowed_repos.json: |-
    {
      "allowed": [
        {{- range $index, $repo := .Values.config.allowedRepos }}
        {{- if $index }},{{ end }}"{{ $repo }}"
        {{- end }}
      ]
    }
